//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Com.MvTech.BusinessEntities;

namespace Com.MvTech.BusinessEntities.EBill
{

    public class Bill : BaseEntity
    {
        public virtual object Date
        {
            get;
            set;
        }

        public virtual object ItemCount
        {
            get;
            set;
        }

        public virtual object TotalQuantity
        {
            get;
            set;
        }

        public virtual object BillAmount
        {
            get;
            set;
        }

        public virtual object RoundingOffAmount
        {
            get;
            set;
        }

        public virtual object netBillAmount
        {
            get;
            set;
        }

        public virtual IEnumerable<BillDetsils> BillDetsils
        {
            get;
            set;
        }

    }
}

