//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AccountReceivables
{
	public virtual DateTime DueDate
	{
		get;
		set;
	}

	public virtual int GrossAmount
	{
		get;
		set;
	}

	public virtual int OpenAmount
	{
		get;
		set;
	}

	public virtual IEnumerable<Receipts> Receipts
	{
		get;
		set;
	}

	public virtual Currency Currency
	{
		get;
		set;
	}

	public virtual Document Document
	{
		get;
		set;
	}

}

