//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AccountTransactionDetails
{
	public virtual int Credit
	{
		get;
		set;
	}

	public virtual int Debit
	{
		get;
		set;
	}

	public virtual int Balance
	{
		get;
		set;
	}

	public virtual DateTime TransactionTimeStamp
	{
		get;
		set;
	}

	public virtual Account Account
	{
		get;
		set;
	}

}

