//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Invoice
{
	public virtual DateTime InvoiceDate
	{
		get;
		set;
	}

	public virtual int InvoiceAmount
	{
		get;
		set;
	}

	public virtual int GeneratedBy
	{
		get;
		set;
	}

	public virtual int Tax
	{
		get;
		set;
	}

	public virtual int TotalAmount
	{
		get;
		set;
	}

	public virtual IEnumerable<InvoiceItem> InvoiceItems
	{
		get;
		set;
	}

}

