//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InvoiceItem
{
	public virtual int Rate
	{
		get;
		set;
	}

	public virtual int Quantity
	{
		get;
		set;
	}

	public virtual int TotalAmount
	{
		get;
		set;
	}

	public virtual int ItemType
	{
		get;
		set;
	}

}

