//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Receipts
{
	public virtual DateTime ReceiptDate
	{
		get;
		set;
	}

	public virtual int ReceivedAmount
	{
		get;
		set;
	}

	public virtual int WriteOffAmount
	{
		get;
		set;
	}

	public virtual int ProcessedBy
	{
		get;
		set;
	}

	public virtual PaymentMethod PaymentMethod
	{
		get;
		set;
	}

}

