//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Com.MvTech.BusinessEntities
{

    public class AuditDetails
    {
        public virtual object createdBy
        {
            get;
            set;
        }

        public virtual object modifiedBy
        {
            get;
            set;
        }

        public virtual object createdOn
        {
            get;
            set;
        }

        public virtual object modifiedOn
        {
            get;
            set;
        }

    }
}

