//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Com.MvTech.BusinessEntities
{
    public abstract class BaseEntity
    {
        public virtual int ID
        {
            get;
            set;
        }

        public virtual string Name
        {
            get;
            set;
        }

        public virtual AuditDetails AuditDetails
        {
            get;
            set;
        }

        public virtual bool IsEnabled
        {
            get;
            set;
        }
        public virtual byte[] TimeStamp
        {
            get;
            set;
        }
        //public virtual EntityTracking EntityTracking
        //{
        //    get;
        //    set;
        //}

    }
}
