//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Com.MvTech.BusinessEntities
{
    public class EntityTracking
    {
        public virtual short IsEnabled
        {
            get;
            set;
        }

        public virtual byte [] TimeStamp
        {
            get;
            set;
        }
    }
}
