//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Com.MvTech.BusinessEntities.EBill;

namespace Com.MvTech.BusinessEntities
{
    public class MobilePhone : Phone
    {
        public virtual IEnumerable<Bill> Bills
        {
            get;
            set;
        }
    }
}

