//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Com.MvTech.BusinessEntities
{


    public class State : BaseEntity
    {
        public virtual Country Country
        {
            get;
            set;
        }
        public virtual IList<City> Cities
        {
            get;
            set;
        }
    }
}

