//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BillDetsils : BaseEntity
{
	public virtual object ItemDescription
	{
		get;
		set;
	}

	public virtual object Rate
	{
		get;
		set;
	}

	public virtual object Quantity
	{
		get;
		set;
	}

	public virtual object Discount
	{
		get;
		set;
	}

	public virtual object NetAmount
	{
		get;
		set;
	}

}

