//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BusinessPartner : BaseEntity
{
	public virtual Address communicationAddress
	{
		get;
		set;
	}

	public virtual Address Address
	{
		get;
		set;
	}

}

