//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MobilePhone
{
	public virtual object MobileNumber
	{
		get;
		set;
	}

	public virtual IEnumerable<Bill> Bill
	{
		get;
		set;
	}

}

