//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User : BusinessPartner
{
	public virtual object FirstName
	{
		get;
		set;
	}

	public virtual object Last Name
	{
		get;
		set;
	}

	public virtual object DOB
	{
		get;
		set;
	}

	public virtual object EMail
	{
		get;
		set;
	}

	public virtual object Gender
	{
		get;
		set;
	}

	public virtual object UserId
	{
		get;
		set;
	}

	public virtual IEnumerable<MobilePhone> MobilePhone
	{
		get;
		set;
	}

}

