//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Com.MvTech.BusinessEntities.Security;
using Com.MvTech.BusinessEntities.BP;


namespace Com.MvTech.BusinessEntities.Users
{

    public class User : BusinessPartner
    {
        public virtual string FirstName
        {
            get
            {
                return Name;
            }
            set
            {
                Name = value;
            }
        }

        public virtual string LastName
        {
            get;
            set;
        }

        public virtual DateTime DOB
        {
            get;
            set;
        }

        public virtual string EMail
        {
            get;
            set;
        }

        public virtual int Gender
        {
            get;
            set;
        }

        public virtual int MobilePhone
        {
            get;
            set;
        }

        public virtual IEnumerable<MobilePhone> MobilePhones
        {
            get;
            set;
        }

        public virtual IEnumerable<Role> Roles
        {
            get;
            set;
        }

    }

}